// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Persistence;
using System;

namespace Persistence.Migrations
{
    [DbContext(typeof(CloudContext))]
    [Migration("20180503184801_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Domain.Administradora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dv")
                        .HasMaxLength(1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(120);

                    b.Property<int>("Rut")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("Administradora");
                });

            modelBuilder.Entity("Model.Domain.Fondo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AdministradoraId");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20);

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.HasIndex("AdministradoraId");

                    b.ToTable("Fondo");
                });

            modelBuilder.Entity("Model.Domain.Fondo", b =>
                {
                    b.HasOne("Model.Domain.Administradora")
                        .WithMany("Fondo")
                        .HasForeignKey("AdministradoraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
